import Image1 from "../assets/Upendo.jpeg"
import Image2 from "../assets/Faidha.jpeg"
import Image3 from "../assets/Brockline.jpeg"
import Image4 from "../assets/Harith.jpeg"
import Image5 from "../assets/Patric.jpeg"

export type Table = {
  id: string
  name: string
  date: string
  time: string
  phone: string
  email: string
  service: string
  img?: string
  category: "suggestion" | "alert" | "complaint"  | "compliment"
  description: string
  status: "Pending" | "Resolved" | "Closed" | "Received"
}

export const TableDatas: Table[] = [
  {
    id: "1",
    name: "John Doe",
    date: "2025-10-03",
    time: "08:30",
    phone: "123-456-7890",
    email: "johndoes@email.com",
    service: "Software Development",
    category: "suggestion",
    img:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHBlcnNvbnxlbnwwfHwwfHx8MA%3D%3D",
    description: "I appreciate the software development service I received, but I believe there is room to improve customer care. While the technical work was delivered well, communication and responsiveness could be more consistent. Providing faster updates, clearer timelines, and proactive support when challenges arise would help build more trust and confidence. Strengthening customer care in this way will make the overall service experience more professional and customer-friendly.",
    status: "Pending"
  },
  {
    id: "2",
    name: "Jane Smith",
    date: "2025-10-04",
    time: "09:10",
    phone: "987-654-3210",
    email: "janesmith@email.com",
    service: "ICT Research and Consulting",
    category: "alert",
    img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGVyc29ufGVufDB8fDB8fHww",
    description: "This is a sample description for Jane Smith's feedback entry.",
    status: "Resolved"
  },
  {
    id: "3",
    name: "Alice Johnson",
    date: "2025-10-03",
    time: "02:40",
    phone: "555-123-4567",
    email: "alice@123.email.com",
    service: "Software Development",
    category: "complaint",
    img:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGVyc29ufGVufDB8fDB8fHww",
    description: "I appreciate the software development service I received, but I believe there is room to improve customer care. While the technical work was delivered well, communication and responsiveness could be more consistent. Providing faster updates, clearer timelines, and proactive support when challenges arise would help build more trust and confidence. Strengthening customer care in this way will make the overall service experience more professional and customer-friendly.",
    status: "Closed"
  },
  {
    id: "4",
    name: "Juma Shaaban",
    date: "2025-10-04",
    time: "07:24",
    phone: "255780456678",
    email: "jumash@email.com",
    service: "Network Infrastructure Services",
    img:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHBlcnNvbnxlbnwwfHwwfHx8MA%3D%3D",
    category:"compliment",
    description: "This is a sample description for Juma Shaaban's feedback entry.",
    status: "Received"
  },
  {
    id: "5",
    name: "Said Said",
    date: "2025-10-03",
    time: "08:20",
    phone: "255780986678",
    email: "saids@email.com",
    img:"https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHBlcnNvbnxlbnwwfHwwfHx8MA%3D%3D",
    service: "Network Infrastructure Services",
    category: "suggestion",
    description: "This is a sample description for Said said feedback entry.",
    status: "Resolved"
  },
  {
    id: "6",
    name: "Mary John",
    date: "2025-10-03",
    time: "08:20",
    phone: "255757346678",
    email: "saids@email.com",
    img:"https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8cGVyc29ufGVufDB8fDB8fHww",
    service: "ICT Governance, Risk and Compliance",
    category: "alert",
    description: "This is a sample description for Said said feedback entry.",
    status: "Pending"
  },
  {
    id: "7",
    name: "Upendo Ndassa",
    date: "2025-10-01",
    time: "10:20",
    phone: "255617479762",
    email: "ndassa.up@gmail.com",
    service: "Software Development",
    img: Image1,
    category: "suggestion",
    description: "Sijapenda lakini haya. Swala la msosi ni jambo la muhimu mimi kama mteja naomba nikija tena msosi uwepo wa kutosha",
    status: "Resolved"
  },
  {
    id: "8",
    name: "Faidha Mbega",
    date: "2025-10-01",
    time: "09:20",
    phone: "255689744404",
    email: "faydherbatuli@gmail.com",
    img: Image2,
    service: "Professional ICT Training Services",
    category: "suggestion",
    description: "Nimepata good treatment, tumefundishwa vizuri sana na nimejifunza mengi sana",
    status: "Resolved"
  },
  {
    id: "9",
    name: "Faith Masoud",
    date: "2025-10-02",
    time: "11:28",
    phone: "255621500381",
    email: "masoudfaith3@gmail.com",
    service: "Professional ICT Training Services",
    category: "complaint",
    description: "Wanafunzi wa field tupikiwe",
    status: "Closed"
  },
  {
    id: "10",
    name: "Harith Issa",
    date: "2025-10-01",
    time: "08:26",
    phone: "255787900234",
    email: "hariths@gmail.com",
    img: Image4,
    service: "ICT Governance, Risk and Compliance",
    category: "compliment",
    description: "This is a sample description for Harith Issa feedback entry.",
    status: "Received"
  },
  {
    id: "11",
    name: "Patric Johns",
    date: "2025-10-01",
    time: "08:40",
    phone: "255787346567",
    email: "pjohns@gmail.com",
    service: "Software Development",
    img: Image5,
    category: "alert",
    description: "This is a sample description for pjohns feedback entry.",
    status: "Resolved"
  },
  {
    id: "12",
    name: "Brocklin Mushi",
    date: "2025-10-01",
    time: "09:35",
    phone: "255757987051",
    email: "bmushi@gmail.com",
    service: "Network Infrastructure Services",
    img: Image3,
    category: "suggestion",
    description: "This is a sample description for Brockline Mushi feedback entry.",
    status: "Pending"
  },
  {
    id: "13",
    name: "Jovin John",
    date: "2025-10-01",
    time: "12:58",
    phone: "255569832456",
    email: "jjohn@gmail.com",
    service: "Professional ICT Training Services",
    category: "suggestion",
    description: "This is a sample description for Jovin John feedback entry.",
    status: "Pending"
  },
  {
    id: "14",
    name: "Joshua Mkunda",
    date: "2025-10-01",
    time: "08:15",
    phone: "255700111222",
    email: "joshuashauri@email.com",
    service: "Software Development",
    category: "suggestion",
    description: "Great service overall but customer support could improve.",
    status: "Pending",
  },
  {
    id: "15",
    name: "Jane Smith",
    date: "2025-10-01",
    time: "09:30",
    phone: "255711222333",
    email: "jane.smith@email.com",
    img:"https://images.unsplash.com/photo-1438761681033-6461ffad8d80?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    service: "ICT Research and Consulting",
    category: "complaint",
    description: "The consultation was delayed and lacked clarity.",
    status: "Resolved",
  },
  {
    id: "16",
    name: "Alice Johnson",
    date: "2025-10-02",
    time: "11:00",
    phone: "255722333444",
    email: "alice.johnson@email.com",
    service: "Professional ICT Training Services",
    img:"https://unsplash.com/photos/smiling-woman-wearing-white-and-black-pinstriped-collared-top-QXevDflbl8A",
    category: "compliment",
    description: "The trainers were excellent and explained concepts clearly.",
    status: "Received",
  },
  {
    id: "17",
    name: "Michael Brown",
    date: "2025-10-02",
    time: "14:20",
    phone: "255733444555",
    email: "michael.brown@email.com",
    service: "Network Infrastructure Services",
    category: "alert",
    description: "Network downtime occurred during peak hours.",
    status: "Pending",
  },
  {
    id: "18",
    name: "Emily Davis",
    date: "2025-10-02",
    time: "15:45",
    phone: "255744555666",
    email: "emily.davis@email.com",
    service: "Hardware and Systems Maintenance and Support",
    img:"https://unsplash.com/photos/smiling-woman-wearing-white-and-black-pinstriped-collared-top-QXevDflbl8A",
    category: "suggestion",
    description: "Please provide more detailed maintenance reports.",
    status: "Resolved",
  },
  {
    id: "19",
    name: "Daniel Wilson",
    date: "2025-10-03",
    time: "10:10",
    phone: "255755666777",
    email: "daniel.wilson@email.com",
    service: "ICT Governance, Risk and Compliance",
    category: "complaint",
    description: "The compliance process took too long to complete.",
    status: "Closed",
  },
  {
    id: "20",
    name: "Sarah Taylor",
    date: "2025-10-03",
    time: "13:25",
    phone: "255766777888",
    email: "sarah.taylor@email.com",
    service: "Software Development",
    img:"https://unsplash.com/photos/smiling-woman-wearing-white-and-black-pinstriped-collared-top-QXevDflbl8A",
    category: "compliment",
    description: "The team delivered an excellent software solution on time.",
    status: "Received",
  },
  {
    id: "21",
    name: "David Anderson",
    date: "2025-10-03",
    time: "16:00",
    phone: "255777888999",
    email: "david.anderson@email.com",
    service: "ICT Research and Consulting",
    category: "alert",
    description: "A potential data inconsistency was noticed in the research report.",
    status: "Pending",
  },
  {
    id: "22",
    name: "Olivia Martinez",
    date: "2025-10-04",
    time: "09:50",
    phone: "255788999000",
    email: "olivia.martinez@email.com",
    service: "Professional ICT Training Services",
    img:"https://unsplash.com/photos/smiling-woman-wearing-white-and-black-pinstriped-collared-top-QXevDflbl8A",
    category: "suggestion",
    description: "Add more practical labs to the training sessions.",
    status: "Resolved",
  },
  {
    id: "23",
    name: "James Thomas",
    date: "2025-10-04",
    time: "11:30",
    phone: "255799000111",
    email: "james.thomas@email.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "compliment",
    description: "Quick response and professional support team.",
    status: "Received",
  },
  {
    id: "24",
    name: "Sophia White",
    date: "2025-10-04",
    time: "12:40",
    phone: "255710111222",
    email: "sophia.white@email.com",
    service: "Network Infrastructure Services",
    category: "complaint",
    description: "Network instability caused repeated disconnections.",
    status: "Pending",
  },
  {
    id: "25",
    name: "Ethan Harris",
    date: "2025-10-05",
    time: "08:25",
    phone: "255721222333",
    email: "ethan.harris@email.com",
    service: "ICT Governance, Risk and Compliance",
    category: "alert",
    description: "Detected unusual system access attempts.",
    status: "Closed",
  },
  {
    id: "26",
    name: "Ava Clark",
    date: "2025-10-05",
    time: "09:55",
    phone: "255732333444",
    email: "ava.clark@email.com",
    service: "Software Development",
    category: "suggestion",
    description: "Improve user interface design for better usability.",
    status: "Resolved",
  },
  {
    id: "27",
    name: "William Lewis",
    date: "2025-10-05",
    time: "14:10",
    phone: "255743444555",
    email: "william.lewis@email.com",
    service: "ICT Research and Consulting",
    category: "compliment",
    description: "Very insightful consulting session with actionable outcomes.",
    status: "Received",
  },
  {
    id: "28",
    name: "Mia Walker",
    date: "2025-10-05",
    time: "15:35",
    phone: "255754555666",
    email: "mia.walker@email.com",
    service: "Professional ICT Training Services",
    category: "complaint",
    description: "Training material was outdated and not engaging.",
    status: "Pending",
  },
  {
    id: "29",
    name: "Noah Robinson",
    date: "2025-10-06",
    time: "10:45",
    phone: "255765666777",
    email: "noah.robinson@email.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "alert",
    description: "Hardware failure detected during scheduled checks.",
    status: "Closed",
  },
  {
    id: "30",
    name: "Isabella King",
    date: "2025-10-06",
    time: "11:20",
    phone: "255776777888",
    email: "isabella.king@email.com",
    service: "Network Infrastructure Services",
    category: "compliment",
    description: "Excellent setup of the new office network.",
    status: "Received",
  },
  {
    id: "31",
    name: "Liam Scott",
    date: "2025-10-06",
    time: "13:15",
    phone: "255787888999",
    email: "liam.scott@email.com",
    service: "ICT Governance, Risk and Compliance",
    category: "suggestion",
    description: "Add regular compliance awareness workshops.",
    status: "Pending",
  },
  {
    id: "32",
    name: "Charlotte Green",
    date: "2025-10-06",
    time: "14:50",
    phone: "255798999000",
    email: "charlotte.green@email.com",
    service: "Software Development",
    category: "complaint",
    description: "The software had several bugs at delivery.",
    status: "Closed",
  },
  {
    id: "33",
    name: "Benjamin Adams",
    date: "2025-10-07",
    time: "09:05",
    phone: "255709000111",
    email: "benjamin.adams@email.com",
    service: "ICT Research and Consulting",
    category: "alert",
    description: "Important research data missing from the report.",
    status: "Resolved",
  },
  {
    id: "34",
    name: "Debra Jones",
    date: "2025-10-05",
    time: "10:48",
    phone: "255522650312",
    email: "daniel39@gmail.com",
    service: "ICT Governance, Risk and Compliance",
    category: "compliment",
    description: "Cold stand remain people culture degree call.",
    status: "Received"
  },
  {
    id: "35",
    name: "John Benson",
    date: "2025-10-07",
    time: "14:18",
    phone: "255628195383",
    email: "phyllis84@hotmail.com",
    service: "ICT Research and Consulting",
    category: "complaint",
    description: "Suddenly performance everything water fight author discuss.",
    status: "Closed"
  },
  {
    id: "36",
    name: "Carol Davis",
    date: "2025-10-06",
    time: "09:32",
    phone: "255423397487",
    email: "ycastillo@hotmail.com",
    service: "Professional ICT Training Services",
    category: "suggestion",
    description: "Phone friend power board group edge career.",
    status: "Closed"
  },
  {
    id: "37",
    name: "James Hill",
    date: "2025-10-05",
    time: "13:04",
    phone: "255798329223",
    email: "james37@hotmail.com",
    service: "Software Development",
    category: "alert",
    description: "Husband material true common action nearly news.",
    status: "Pending"
  },
  {
    id: "38",
    name: "Nathaniel Roberts",
    date: "2025-10-08",
    time: "01:54",
    phone: "255436527031",
    email: "jacob91@yahoo.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "compliment",
    description: "Professor music win sense information maybe since.",
    status: "Received"
  },
  {
    id: "39",
    name: "Nicole Miller",
    date: "2025-10-08",
    time: "12:15",
    phone: "255652055599",
    email: "james04@gmail.com",
    service: "Network Infrastructure Services",
    category: "suggestion",
    description: "Reason knowledge final necessary reduce tax card.",
    status: "Pending"
  },
  {
    id: "40",
    name: "Heather Thomas",
    date: "2025-10-02",
    time: "16:52",
    phone: "255652190742",
    email: "kennethdavis@hotmail.com",
    service: "ICT Governance, Risk and Compliance",
    category: "compliment",
    description: "Able staff season pull fight but.",
    status: "Received"
  },
  {
    id: "41",
    name: "Taylor Johnson",
    date: "2025-10-02",
    time: "20:15",
    phone: "255883675808",
    email: "stephanie45@gmail.com",
    service: "ICT Research and Consulting",
    category: "complaint",
    description: "Include until hand understand enjoy hundred catch.",
    status: "Pending"
  },
  {
    id: "42",
    name: "Erik Gonzalez",
    date: "2025-10-01",
    time: "03:05",
    phone: "255521539430",
    email: "owenfreeman@gmail.com",
    service: "Professional ICT Training Services",
    category: "alert",
    description: "Life every song theory together take reach.",
    status: "Resolved"
  },
  {
    id: "43",
    name: "Nicholas Sanchez",
    date: "2025-10-09",
    time: "08:30",
    phone: "255773792477",
    email: "sherrycoleman@gmail.com",
    service: "Software Development",
    category: "suggestion",
    description: "Mother become million air energy thank indeed.",
    status: "Resolved"
  },
  {
    id: "44",
    name: "Danielle Clark",
    date: "2025-10-09",
    time: "23:20",
    phone: "255768445179",
    email: "jacksoncheryl@hotmail.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "complaint",
    description: "Offer answer sure into control describe floor.",
    status: "Closed"
  },
  {
    id: "45",
    name: "Sara Hall",
    date: "2025-10-06",
    time: "07:55",
    phone: "255564102331",
    email: "qgates@hotmail.com",
    service: "Network Infrastructure Services",
    category: "alert",
    description: "Big appear culture boy experience management act.",
    status: "Closed"
  },
  {
    id: "46",
    name: "Elizabeth Wilson",
    date: "2025-10-01",
    time: "05:11",
    phone: "255738054420",
    email: "elizabethjohnson@gmail.com",
    service: "ICT Governance, Risk and Compliance",
    category: "compliment",
    description: "Place toward behind class view high few.",
    status: "Received"
  },
  {
    id: "47",
    name: "Michael Martinez",
    date: "2025-10-03",
    time: "15:41",
    phone: "255619230064",
    email: "daniel01@yahoo.com",
    service: "ICT Research and Consulting",
    category: "compliment",
    description: "Society simple fire effect situation learn.",
    status: "Received"
  },
  {
    id: "48",
    name: "Michael Smith",
    date: "2025-10-01",
    time: "06:27",
    phone: "255037461004",
    email: "jennifer10@yahoo.com",
    service: "Professional ICT Training Services",
    category: "complaint",
    description: "Story experience against beat put need best.",
    status: "Resolved"
  },
  {
    id: "49",
    name: "Amy Jackson",
    date: "2025-10-04",
    time: "11:49",
    phone: "255566349807",
    email: "nancy72@yahoo.com",
    service: "Software Development",
    category: "complaint",
    description: "Support after never guess perform possible.",
    status: "Pending"
  },
  {
    id: "50",
    name: "Justin Miller",
    date: "2025-10-10",
    time: "04:00",
    phone: "255398074159",
    email: "hubbardmargaret@hotmail.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "alert",
    description: "Apply under television civil during majority.",
    status: "Closed"
  },
  {
    id: "51",
    name: "Austin Johnson",
    date: "2025-10-04",
    time: "02:35",
    phone: "255743605531",
    email: "suttonkevin@hotmail.com",
    service: "Network Infrastructure Services",
    category: "suggestion",
    description: "Yes street own heart protect whatever million.",
    status: "Resolved"
  },
  {
    id: "52",
    name: "Angela Henderson",
    date: "2025-10-05",
    time: "19:38",
    phone: "255952837106",
    email: "hernandezdavid@hotmail.com",
    service: "ICT Governance, Risk and Compliance",
    category: "complaint",
    description: "Fine think quickly media alone marriage.",
    status: "Closed"
  },
  {
    id: "53",
    name: "Mark Davis",
    date: "2025-10-07",
    time: "12:00",
    phone: "255580572881",
    email: "eprice@yahoo.com",
    service: "ICT Research and Consulting",
    category: "alert",
    description: "Language all around black read garden part.",
    status: "Resolved"
  },
  {
    id: "54",
    name: "Emily Lewis",
    date: "2025-10-02",
    time: "09:14",
    phone: "25530789407",
    email: "emily.lewis@gmail.com",
    service: "Professional ICT Training Services",
    category: "suggestion",
    description: "Improve training materials to include more real-world scenarios.",
    status: "Pending"
  },
  {
    id: "55",
    name: "Matthew Turner",
    date: "2025-10-03",
    time: "11:47",
    phone: "25591836502",
    email: "mturner@yahoo.com",
    service: "Software Development",
    category: "compliment",
    description: "The new software system exceeded expectations in speed and usability.",
    status: "Received"
  },
  {
    id: "56",
    name: "Sophia Scott",
    date: "2025-10-06",
    time: "13:22",
    phone: "25571529860",
    email: "sophiascott@hotmail.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "complaint",
    description: "Maintenance response times were longer than expected.",
    status: "Closed"
  },
  {
    id: "57",
    name: "William Anderson",
    date: "2025-10-04",
    time: "15:55",
    phone: "255884056223",
    email: "william.anderson@gmail.com",
    service: "Network Infrastructure Services",
    category: "alert",
    description: "Detected irregular network activity during peak hours.",
    status: "Pending"
  },
  {
    id: "58",
    name: "Olivia Martinez",
    date: "2025-10-05",
    time: "08:40",
    phone: "25573971549",
    email: "olivia.martinez@gmail.com",
    service: "ICT Governance, Risk and Compliance",
    category: "compliment",
    description: "Compliance audit support was professional and efficient.",
    status: "Received"
  },
  {
    id: "59",
    name: "Daniel Thomas",
    date: "2025-10-06",
    time: "12:20",
    phone: "255728710657",
    email: "danielthomas@gmail.com",
    service: "ICT Research and Consulting",
    category: "suggestion",
    description: "Include more industry benchmarks in consulting reports.",
    status: "Pending"
  },
  {
    id: "60",
    name: "Ava Wilson",
    date: "2025-10-07",
    time: "10:18",
    phone: "255398450021",
    email: "ava.wilson@yahoo.com",
    service: "Professional ICT Training Services",
    category: "complaint",
    description: "Training sessions were too short for the complexity of topics.",
    status: "Closed"
  },
  {
    id: "61",
    name: "Christopher Robinson",
    date: "2025-10-02",
    time: "14:11",
    phone: "255928104761",
    email: "crobinson@gmail.com",
    service: "Software Development",
    category: "alert",
    description: "Critical bug found in the accounting module.",
    status: "Pending"
  },
  {
    id: "62",
    name: "Mia Johnson",
    date: "2025-10-08",
    time: "16:47",
    phone: "255792835007",
    email: "mia.johnson@hotmail.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "compliment",
    description: "Hardware replacement was fast and seamless.",
    status: "Received"
  },
  {
    id: "63",
    name: "Ethan Harris",
    date: "2025-10-01",
    time: "09:35",
    phone: "255783745129",
    email: "ethan.harris@gmail.com",
    service: "Network Infrastructure Services",
    category: "suggestion",
    description: "Consider expanding network bandwidth for peak usage hours.",
    status: "Pending"
  },
  {
    id: "64",
    name: "Abigail Clark",
    date: "2025-10-09",
    time: "18:25",
    phone: "255738175200",
    email: "abigail.clark@yahoo.com",
    service: "ICT Governance, Risk and Compliance",
    category: "complaint",
    description: "Some compliance reports had missing references.",
    status: "Closed"
  },
  {
    id: "65",
    name: "Alexander Walker",
    date: "2025-10-04",
    time: "07:50",
    phone: "255703487652",
    email: "alex.walker@gmail.com",
    service: "ICT Research and Consulting",
    category: "alert",
    description: "Outdated industry data used in analysis.",
    status: "Pending"
  },
  {
    id: "66",
    name: "Ella King",
    date: "2025-10-07",
    time: "20:42",
    phone: "255938104567",
    email: "ellaking@gmail.com",
    service: "Professional ICT Training Services",
    category: "compliment",
    description: "Trainer was very knowledgeable and engaging.",
    status: "Received"
  },
  {
    id: "67",
    name: "Benjamin Wright",
    date: "2025-10-03",
    time: "17:10",
    phone: "25591048309",
    email: "benwright@gmail.com",
    service: "Software Development",
    category: "complaint",
    description: "User interface is not mobile-friendly.",
    status: "Closed"
  },
  {
    id: "68",
    name: "Charlotte Hall",
    date: "2025-10-08",
    time: "15:30",
    phone: "255738245001",
    email: "charlotte.hall@yahoo.com",
    service: "Hardware and Systems Maintenance and Support",
    category: "alert",
    description: "Power failure caused temporary hardware issues.",
    status: "Pending"
  },
  {
    id: "69",
    name: "Henry Allen",
    date: "2025-10-06",
    time: "10:29",
    phone: "255918745098",
    email: "henry.allen@gmail.com",
    service: "Network Infrastructure Services",
    category: "compliment",
    description: "Network upgrade improved overall performance.",
    status: "Received"
  },
  {
    id: "70",
    name: "Amelia Young",
    date: "2025-10-02",
    time: "13:45",
    phone: "255709712507",
    email: "amelia.young@gmail.com",
    service: "ICT Governance, Risk and Compliance",
    category: "suggestion",
    description: "Add more detailed guidelines for compliance documentation.",
    status: "Pending"
  },
  {
    id: "71",
    name: "David Hernandez",
    date: "2025-10-05",
    time: "21:14",
    phone: "255728195602",
    email: "david.hernandez@hotmail.com",
    service: "ICT Research and Consulting",
    category: "complaint",
    description: "Consulting recommendations lacked actionable steps.",
    status: "Closed"
  },
  {
    id: "72",
    name: "Harper Lopez",
    date: "2025-10-07",
    time: "08:55",
    phone: "255718356028",
    email: "harper.lopez@gmail.com",
    service: "Professional ICT Training Services",
    category: "alert",
    description: "Technical issue during the online training session.",
    status: "Pending"
  },
  {
    id: "73",
    name: "Joseph Green",
    date: "2025-10-09",
    time: "19:05",
    phone: "255804715092",
    email: "joseph.green@gmail.com",
    service: "Software Development",
    category: "compliment",
    description: "Custom software delivered ahead of schedule.",
    status: "Received"
  },
]



